---

- name: "Unzip copied file"
  become: true
  unarchive:
    src: files/artifact.tar.gz
    dest: .

- name: "Run pm2"
  become: true
  shell: |
    npm install
    pm2 stop all
    pm2 start npm --name "udapeople-backend" -- run start
  environment:
    ENVIRONMENT: production
    NODE_ENV: production
    TYPEORM_CONNECTION: postgres
    TYPEORM_MIGRATIONS_DIR: ./src/migrations
    TYPEORM_ENTITIES: ./src/modules/**/*.entity.ts
    TYPEORM_MIGRATIONS: ./src/migrations/*.ts
    TYPEORM_HOST: database-1.ca0dyn9wwwju.us-east-1.rds.amazonaws.com
    TYPEORM_PORT: "5432"
    TYPEORM_USERNAME: postgres
    TYPEORM_PASSWORD: mypassword
    TYPEORM_DATABASE: postgres