---

- name: "Copy file to the server"
  become: true
  copy:
    src: artifact.tar.gz
    dest: /home/ubuntu

- name: "Unzip copied file"
  become: true
  unarchive:
    src: artifact.tar.gz
    dest: /home/ubuntu

- name: "Install npm"
  become: true
  shell:
    cmd: "npm install"

- name: "Run pm2"
  become: true
  shell:
    cmd: |
      pm2 stop default
      pm2 start npm --name "udapeople-backend" -- run start

- name: "Set pm2 start as service"
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup -u ubuntu

- name: check pm2 status
  become: true
  shell: |
    pm2 describe "udapeople-backend"
  register: command_output_npm
- debug: var=command_output_npm.stdout_lines