---

- name: "Copy file to the server"
  become: true
  copy:
    src: artifact.tar.gz
    dest: /home/ubuntu

- name: "Unzip copied file"
  become: true
  unarchive:
    src: artifact.tar.gz
    dest: /home/ubuntu

- name: "Run pm2"
  become: true
  shell: |
    npm install
    pm2 stop all
    pm2 start npm --name "udapeople-backend" -- run start
