- name: extract artifact
  become: true
  unarchive:
    src: files/artifact.tar.gz
    dest: .

- name: "Install npm"
  become: true
  shell:
    cmd: "npm install"

- name: "Run pm2"
  become: true
  shell:
    cmd: "pm2 stop default || pm2 start npm -- start"
